---
version: '2.2'
services:
  synchronizer:
    build:
      context: synchronizer
    container_name: synchronizer
    environment:
      KAFKA_BROKERS: "kafka-1:19092,kafka-2:19094,kafka-3:19096"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
