---
version: '2.2'
services:

  axon-server:
    image: axoniq/axonserver:4.4.5
    container_name: axon
    ports:
      - "8024:8024"
      - "8124:8124"
    mem_limit: 400m
    restart: always

volumes:
  kafka-graphql-certs:
    external: true

