---
version: '2.2'
services:

  command-handler:
    build:
      context: command-handler
    container_name: command-handler
    environment:
      AXON_AXONSERVER_SERVERS: "axon-server"
    volumes:
      - kafka-graphql-certs:/etc/kafka/secrets
    mem_limit: 2000m
    restart: always

  projector:
    build:
      context: projector
    container_name: projector
    depends_on:
      - command-handler
    environment:
      AXON_AXONSERVER_SERVERS: "axon-server"
    mem_limit: 2000m
    restart: always

  graphql-endpoint:
    build:
      context: graphql-endpoint
    container_name: graphql-endpoint
    ports:
      - "8888:8888"
    depends_on:
      - command-handler
      - projector
    environment:
      AXON_AXONSERVER_SERVERS: "axon-server"
    volumes:
      - kafka-graphql-certs:/etc/kafka/secrets
    mem_limit: 2000m
    restart: always

  frontend:
    build:
      context: frontend
    container_name: frontend
    ports:
      - "8181:80"
    depends_on:
      - graphql-endpoint
    environment:
      - NGINX_PORT=80
    restart: always

volumes:
  kafka-graphql-certs:
    external: true
